Implement internal math module
paxproject/pax pull request #114
Opened 2024-02-16 18:55 UTC by samuelselleck

This implements an internal math module, to be exposed to users of pax, and removes the use of kurbo::Affine as the engines main transform type.

2024-02-16 19:36 UTC, zackbrown requested changes
Nice improvements!  Small changes requested re: `design_utils`, per team conversation.  After that, please go ahead and merge directly.

2024-02-16 19:36 UTC, zackbrown commented on pax-engine/src/lib.rs
> +pub use pax_runtime::design_utils;
please remove

2024-02-16 19:36 UTC, zackbrown commented on pax-runtime/src/engine/design_utils.rs
please remove

2024-02-16 19:36 UTC, zackbrown commented on pax-runtime/src/engine/mod.rs
> +pub mod design_utils;
please remove

2024-02-16 21:49 UTC, samuelselleck commented
This is done now! 
- Created a new NodeInterface type that is a public wrapper over ExpandedNode
- Added methods on NodeContext to do raycasting, finding by id, etc (forwarding calls to render_context and wrapping results in NodeInterface)
- Renamed NodeContext to EngineContext to better reflect it's ability to do things like global raycasting

2024-02-17 01:59 UTC, warfaj commented
LGTM! Thanks for the changes.

2024-02-17 01:59 UTC, merged